workflows:
  ios-workflow:
    name: iOS Internal TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...)
        BUNDLE_ID: "com.bimmerwise.app"

    scripts:
      - name: Flutter clean
        script: flutter clean

      - name: Get dependencies
        script: flutter pub get

      - name: Install pods
        script: |
          cd ios
          pod install

      - name: Code signing
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          BUILD_NUMBER=$(date +%s)
          flutter build ipa \
            --release \
            --export-method=app-store \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

      email:
        recipients:
          - deniel080@gmail.com
        notify:
          success: true
          failure: true
