// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG2cm42EfbE1FU2pnC808BuVkxGKELong',
    appId: '1:305192442938:web:9196c903d9dbc7e6592903',
    messagingSenderId: '305192442938',
    projectId: 'bimmerwise-9c7bd',
    authDomain: 'bimmerwise-9c7bd.firebaseapp.com',
    storageBucket: 'bimmerwise-9c7bd.firebasestorage.app',
    measurementId: 'G-XS72XNMEXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5YMtIDFPMto4DBuE-R_QYWiHRs86b7VQ',
    appId: '1:305192442938:android:822047f1759dfc66592903',
    messagingSenderId: '305192442938',
    projectId: 'bimmerwise-9c7bd',
    storageBucket: 'bimmerwise-9c7bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADTOnGsFxFApGNuqwOu7BiAb62pjI9c7M',
    appId: '1:305192442938:ios:872f2b3c30e46c05592903',
    messagingSenderId: '305192442938',
    projectId: 'bimmerwise-9c7bd',
    storageBucket: 'bimmerwise-9c7bd.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
